### ISSUE TITLE
Cameron's review

### ISSUE THREAD

**Issue by CameronFRWatson** [2020-bgmp/demultiplexing-megan-criss#2]
## Specific Notes

Line 61-69: This function would have to read through all of the files, editing R1 and R4 and iterating through all of the lines before looping through again for demultiplexing. Because these files are absolutely massive, this would take a really long time. Instead, it would be more efficient to add the indices to the header lines as you loop through the files to demultiplex, that way you only have to loop through them once. This function is also called from within the block beginning at line 88 which calls it while looping through to demultiplex. The block beginning at line 88 seems great, I think the add_indexes function needs to be adjusted to fit with it.

Lines 101 and 110: I could totally be reading this incorrectly, but why check for correct indices twice for the same set of records? Seems redundant 

## Checklist

Outputs matched/hopped/unknown into separate files, split by forward and reverse reads

Keeps counter for index pair permutations, matched, hopped, and unknown/low quality, outputs to separate file

## Final Notes

I was having a bit of trouble following the logic of the main block of code (beginning at line 88); however, all of the pieces are there. There are discrete functions  and all have logical outputs (aside from add_indexes which I think needs tweaking), and there do seem to be methods for parsing to separate files. I think that how these pieces work together in an efficient way is where I get a bit lost, but otherwise seems like the right track! 

p.s. Sorry if some of these notes don't make sense, it's hard to phrase a lot of this stuff!

**Comment by megan-criss** [comment]
Thank you so much for your review Cameron, it has helped me a lot and I definitely need to tweak some stuff! I agree with you that my code is not very efficient and that some of my functions don't make too much sense. I will definitely take your suggestions and use them for my final algorithm so thank you!
