### ISSUE TITLE
Jonas Code Review

### ISSUE THREAD

**Issue by Jonasgrove** [2020-bgmp/demultiplexing-megan-criss#3]
##Megan
//function Line 48
    •consider when there is a nucleotide of N unless you check before that outside function

//function line 77
    •consider making all index permutations once outside function
    instead of making them every function call
    •consider using a dictionary to look up index hop pairs instead of iterating
    through a whole list, will save you some time.
//match line 88
    •would possibly advise against storing the file contents in a numpy array as will take up a lot of memory
    •consider checking if quality is poor as your first conditional statement, because this condition 
    overrides all other conditions.
    •check out using elif (else if), it will kinda do what your describing with 'but'
    •not entirely sure where you are looping, but it seems like that is implied. 
    if you wanna iterate through all files at once, check out itertools zip(list, list, list, list)

Does the proposed algorithm make sense to you? Can you follow the logic?
    yes it seems that you have the right idea, maybe = try and adjust the conditional statements
    in the last section so that you are not checking the quality multiple times, but seems like it would work

Does the algorithm do everything it's supposed to do? (see list of requirements in Assignment the First)
    yeah all the high level pieces are there, looks like you are on the right track

Are proposed functions reasonable? Are they "standalone" pieces of code?
    yes the functions are well described, the last section could be a little more clear, but 
    you seem to have the right idea.

**Comment by megan-criss** [comment]
Thank you so much for your review Jonas, it has helped me a lot and I definitely need to tweak some stuff! I think my code is a little inefficient and confusing at times, so I will definitely take your suggestions and use them for my final algorithm.  Thank you!
